### ISSUE TITLE
would `sheet-router` work well with yoyo?

### ISSUE THREAD

**Issue by SilentCicero** [yoshuawuyts/sheet-router#12]
@yoshuawuyts  Would this router work well with bel/yoyo/morphdom?

**Comment by yoshuawuyts** [comment]
Hell yeah - https://github.com/yoshuawuyts/playground-yoyo/blob/master/index.js

I'd stay away from the `bridge.js` file though, it's even confusing me (and I wrote it). Apart from that all should work well. Let me know if you run into any issues :sparkles:
