### ISSUE TITLE
Support for hash history?

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/sheet-router#16]
Hi @yoshuawuyts, I stumbled upon choo this morning and it's like you were reading my mind! Started my react app over in it but ran into a roadblock: as far as I know, electron apps don't support that html5 browser history thing where you can use `/routes`, so you instead have to use hash history `#routes`. React router has an option for either. Does sheet-router?

**Comment by yoshuawuyts** [comment]
Oh yeah, good point! I never got around to adding that - but it should probably have it. Ummm, I'm a bit out of it right now, but how about I cook something up one of these days? If I haven't come up with something halfway this week feel free to ping me again. Cheers!

**Comment by timwis** [comment]
Thanks. Looking further into it, I suppose this issue should have been posted in choo, since that framework is what activates the browser history bit. Anyway, if you can give me a hint I'm happy to make an attempt if you're busy. Unfortunately I haven't been able to use choo without this piece, as it requires a router be initialized. Thanks for your help though.

**Comment by timwis** [comment]
Just that friendly reminder you asked for :) let me know if there's a way to use another router in the meantime (I've spent a lot of time trying), or if I can help with a PR. Thanks for your help!

**Comment by yoshuawuyts** [comment]
@timwis sorry, been super busy :( - if you've got a great idea, feel free to share!

**Comment by yoshuawuyts** [comment]
Closed by #18, released as `v3.1.0`
