### ISSUE TITLE
async routes

### ISSUE THREAD

**Issue by gmaclennan** [yoshuawuyts/sheet-router#20]
How would I implement async routes that need to load data before rendering the route?

**Comment by yoshuawuyts** [comment]
I'd create two views and switch between them whether or not there's data. I don't think data fetching and reacting to data are a concern of the router; they should be handled in controllers / models / views (or whichever words you prefer) respectively. 

I hope this answers your question. Cheers!

**Comment by yoshuawuyts** [comment]
I'm closing this for now as I think it'll resolve your issue. Def welcome to reopen and discuss it more if it doesn't. Cheers!

**Comment by blocka** [comment]
How would you implement something like protecting routes that require authentication, or preventing navigation until a form is saved?

**Comment by yoshuawuyts** [comment]
This is all logic, that doesn't have anything to do with the actual router. e.g. you could do something like:
```js
const sheetRouter = require('sheet-router')
const html = require('yo-yo')
const router = sheetRouter((route) => [
  route('/profile', (params, state) => {
    if (!state.username) {
      return html`<div>user not logged in, please log in</div>`
    } else {
      return html`<div>user's logged in, yay!</div>`
    }
  })
])

router('/profile', { username: 'samantha' })
```
I suggest you take a look at [choo](https://github.com/yoshuawuyts/choo) for a framework that works with these ideas
