### ISSUE TITLE
'/404' question

### ISSUE THREAD

**Issue by dfcreative** [yoshuawuyts/sheet-router#21]
Hi @yoshuawuyts!
I am playing with choo and trying to do the router thing described in readme:
```js
app.router('/404', (route) => [
	route('/', mainView),
	route('/404', errorView)
	// route('/:mailbox', require('./views/mailbox'), [
	// 	route('/:message', require('./views/email'))
	// ])
])
```
And it gives an error: 
```
assert.js:59Uncaught AssertionError: createTree must be a function
```
Removing `/404` at the beginning fixes the issue.

But I was curious what is the meaning of that initial `/404` directive, which is duplicated in route later on.
So I decided to check that with `sheet-router`.
```js
const router = sheetRouter('/404', function (route) {
  return [
    route('/', (params) => yo`<div>Welcome to router land!</div>`),
    route('/:username', (params) => yo`<div>${params.username}</div>`, [
      route('/orgs', (params) => yo`<div>${params.username}'s orgs!</div>`)
    ])
  ]
})
```
I tried to figure out any difference if I skip that first directive and I didn’t get it. What does skipping it change? Without that the whole thing seems more clear to me, but I can’t wrap my head over it. Is it just a name of router?
I feel confused.

**Comment by dfcreative** [comment]
Ok, it is the default path, I should’ve read readme carefully before. But still, choo crashes with the error.

**Comment by yoshuawuyts** [comment]
Oops, yeah that's no good. Thanks for reporting! So I should do two things:
- [ ] update docs so that it's more clear it's the default path
- [ ] fix this bug

**Comment by yoshuawuyts** [comment]
Hmm, oddly enough I'm testing for it already here - https://github.com/yoshuawuyts/sheet-router/blob/master/test.js#L25-L37; not sure what's going wrong - digging deeper

**Comment by yoshuawuyts** [comment]
@dfcreative just to verify: is this only happening in `choo` or also in `sheet-router`?

**Comment by yoshuawuyts** [comment]
I've updated the docs in 17c36ea

**Comment by dfcreative** [comment]
sheet-router is fine, only happens with choo. Thanks for the docs!

**Comment by yoshuawuyts** [comment]
Ah alright, then I'm going to close this one and open a new one on `choo`. Thanks again for reporting!
