### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by blocka** [yoshuawuyts/sheet-router#22]
As far as I can tell, nested routes only serve to make nested urls. The end result is replacing the whole view with the view returned from route.
How would handle a situation where a parent route view acts more like a layout, and the children would be rendered inside that layout (think about a view with a nav and a "content" area).

I tried to look at the choo framework for inspiration, but I don't see anything like that there.

**Comment by yoshuawuyts** [comment]
> As far as I can tell, nested routes only serve to make nested urls

Yup, that's entirely right. Composing views is not the concern of the router here. If you want to compose views you'll have to do that yourself.

That said I do see what you're saying; it would be an interesting experiment to see if we could add that, but not sure it would be better tbh. Hope this answers your question. Cheers!

**Comment by timwis** [comment]
This is a choo example, but I had the same question recently and here's the approach I took: the [router](https://github.com/timwis/dataface/blob/master/public/src/index.js#L12) uses a "high order function" (a function that returns a function) as the view so it can pass a "variant" / subview:

https://github.com/timwis/dataface/blob/master/public/src/views/database-layout.js

**Comment by yoshuawuyts** [comment]
@blocka does this answer your question?

**Comment by blocka** [comment]
Answers my question, but doesn't make me happy. In @timwis 's example, he's exchanged DRY routes for unDRY code (the component has to be repeated in each route).

**Comment by yoshuawuyts** [comment]
> he's exchanged DRY routes for unDRY code

Yeah, I see what you mean. I don't think there's a right or wrong here though; what you're proposing is completely valid - we've just taken a different approach here with `sheet-router`.

With DRYness comes the introduction of abstractions. And each abstraction leads to a bit of overhead that needs to be learned. With the solution you're proposing we'd push composition from the individual view to be a concern of the router, and thus the router would need to deal with that. From my perspective this would mean that the views in the router in addition to `params` / `no params` now need to be aware of `childView` / `no childView` which in turn means that the amount of external abstraction leakage has now grown exponentially (2 possible states -> 4 possible states).

Instead the path `sheet-router` takes is concern itself only with routing. The leakage it provides is that sometimes a view is injected with `params` sometimes - I find that to be acceptable. By not composing views each view has to be explicit what it's made up of. Is this ideal? Who knows - but it's the tradeoff we've chosen here for this design.

I hope this sheds a bit of light on the reasoning behind _why_ things are like they are. Cheers! :sparkles:

**Comment by blocka** [comment]
No problem. There is no one right tool for every job, and I'm sure that many applications would benefit from the philosophy of this router. It just doesn't fit easily into the types of SPA's I normally build.

**Comment by yoshuawuyts** [comment]
Cool; looks like we've got different views then. I reckon this issue can be closed; thanks for opening it - it definitely made me think a bit about _why_ we're doing things the way we do. Happy to discuss it further any time :sparkles: :D
