### ISSUE TITLE
ditch the route() argument

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/sheet-router#29]
As @ahdinosaur pointed out to me today, the API could be a lil bit cleaner if we ditch the `route()` argument:
```js
app.router('/404', [
  ['/', myView],
  ['/404', defaultView],
  ['/foo', myFooView, [
    ['/bar', myOtherView],
    ['/baz', yetAnotherView]
  ]]
])
```
What do people think?

**Comment by yoshuawuyts** [comment]
I think a tiny hello world router could then become:
```js
app.router(['/', myView])
```

**Comment by ahdinosaur** [comment]
@yoshuawuyts what would happen when you don't specify a default, as in your hello world example? in [my setup](https://github.com/ahdinosaur/inux/blob/master/createRouter.js) i used the last route as the default.

**Comment by timwis** [comment]
:+1: to both ideas

**Comment by yoshuawuyts** [comment]
@ahdinosaur we could just detect if an arg was passed in - right now we throw if an incorrect path is called and we don't have a default path. I kinda like having it as the first arg; not too fond of magic tailing arguments haha - much rather switch arg order (':

**Comment by ahdinosaur** [comment]
@yoshuawuyts yeah that makes sense. my question is that if you call `sheetRouter` with a single `routes` argument, what is the default? i see you set `dft` to `''`, does that mean the root path (`/`) is the default? or does it throw if no other path matches like you say? happy with whatever, just want to make sure i understand what the behavior is.

**Comment by yoshuawuyts** [comment]
aye, so not setting a route; (`''` or w/e) should make paths throw. Not sure if you can set `/` to be the default path (oops), but at least yeah that's the idea
