### ISSUE TITLE
Handle hashes by default, in addition to normal paths

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/sheet-router#31]
Right now there's trouble in hash land. When resolving routes it's either normal routing OR hash routing. It'd be nice if we could resolve these in addition to normal paths.

E.g. these paths can be problematic:
- `/foo/bar#baz`
- `/foo/bar` and `/#hey`

Paths could then be represented reflecting the actual values in the url bar, removing the need for `hash.js` and remove the need for [chunky switching logic](https://github.com/yoshuawuyts/choo/blob/dd88941d774aea03ffc061cb75a93cc5a7d8cbcc/index.js#L151-L160).

Possibly separate issue:

We're also not resolving query strings at the moment, perhaps we should add them in params too? Or pass in an extra object containing querystrings as an object? idk

**Comment by timwis** [comment]
+1 for query strings, was just thinking about that

**Comment by yoshuawuyts** [comment]
> We're also not resolving query strings at the moment, perhaps we should add them in params too? Or pass in an extra object containing querystrings as an object? idk

Imo this shouldn't ever impact the routing - if query strings need to be resolved this could be done in a separate function. Perhaps we should provide that - I reckon the node `querystring` package is too big to include so find a separate solution.

**Comment by yoshuawuyts** [comment]
landed in `sheet-router@4` somewhere
