### ISSUE TITLE
fix docs

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/sheet-router#41]
lol what's going on here

<img width="1280" alt="screen shot 2016-08-18 at 18 07 41" src="https://cloud.githubusercontent.com/assets/2467194/17781211/b5a756e0-656e-11e6-98c3-d00f0cac5a69.png">

**Comment by jliuhtonen** [comment]
Fixed [in this PR](https://github.com/yoshuawuyts/sheet-router/pull/42).
