### ISSUE TITLE
Transpile ES6 to ES5, bundle as a UMD module

### ISSUE THREAD

**Issue by jliuhtonen** [yoshuawuyts/sheet-router#43]
If you need to support an environment that does not support ES6 (`const` etc.) and modules (like some browsers), it would be useful if sheet-router was packaged as a UMD module transpiled to ES5. This could be achieved with [rollup](https://github.com/rollup/rollup), for example.

**Comment by yoshuawuyts** [comment]
We're sorta doing the same in `choo` rn - https://github.com/yoshuawuyts/choo/blob/master/package.json#L17

A PR to add that for `sheet-router` would be welcome

**Comment by mAAdhaTTah** [comment]
Was just going to open an issue related to this. The handful of `const` usages are the only ES6 features in use in `sheet-router`, from a quick glance through the codebase. A quick find-replace `const` -> `var` should make the library ES5 compliant. Would that be something you'd be open to?

**Comment by mAAdhaTTah** [comment]
I would also note this affects wayfarer as well.

**Comment by yoshuawuyts** [comment]
nah, I'd rather not - I quite like `const` and `assert` declarations. If you need to optimize for non-greenfield browsers consider running [bundleify](https://github.com/bendrucker/bundleify) - cheers!
