### ISSUE TITLE
Mismatch between documented and published version

### ISSUE THREAD

**Issue by ryenbeatty** [yoshuawuyts/sheet-router#46]
Hi, it would seem that the version matching the docs (3.2.0) has not been published yet, which makes it hard to use at the moment!

Do you plan on publishing 3.2.0 to npm shortly?

Thanks, this looks really neat 🔥

**Comment by yoshuawuyts** [comment]
@ryenbeatty yeah I am, but there's some stuff that needs a bit of fixing first. I was halfway through building `choo@4` when I got side tracked with client projects - should be back on that track soon tho and have this out of the door C:

**Comment by ryenbeatty** [comment]
@yoshuawuyts ah ok, sounds good man 💃
