### ISSUE TITLE
Missing walk.js

### ISSUE THREAD

**Issue by wcastand** [yoshuawuyts/sheet-router#52]
when i ``` npm install sheet-router ```

I can't require 'sheet-router/walk' because it doesn't exist.
<img width="191" alt="capture d ecran 2016-10-04 a 10 18 20" src="https://cloud.githubusercontent.com/assets/2178244/19066935/1f98b374-8a1c-11e6-8f6b-362a97922d65.png">

npm install version 3.1.1

**Comment by yoshuawuyts** [comment]
oh yeah maybe it's missing from files hah

**Comment by yoshuawuyts** [comment]
oh no, yeah this should be in `npm i sheetify@next` - damn, I should totes release this choo v4 thing hah
