### ISSUE TITLE
v4.0.2: `href` and `history` callbacks provided different args

### ISSUE THREAD

**Issue by mAAdhaTTah** [yoshuawuyts/sheet-router#55]
I'm using `sheet-router` for an SPA I'm working on. I was hoping to share the callback passed to both `href` & `history`, but the callbacks get called with different parameters (one with an object, the other with the string). I'm a little confused, because `master` doesn't have this mismatch, so I'm also a little lost on what version(s) is on master vs. 4.0.2.

Would it be possible to harmonize the values passed to those callbacks?

**Comment by yoshuawuyts** [comment]
you're entirely right, I totes missed this. Pushed this in https://github.com/yoshuawuyts/sheet-router/pull/54 and should be fixed now. Released as `v4.0.3`
