### ISSUE TITLE
Late to the partayyyy

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/sheet-router#61]
Oh hey. Been meaning to mention this but I know I'm late to the party. Thought I'd throw it out there before 4 is dropped just in case you're interested.

I was just wondering since the first param of sheet-router is optional, why not make it the last param?

ie. instead of:

```javascript
const app = choo()
app.router({ default: '/404' }, (route) => [
  route('/', require('./views/empty')),
  route('/404', require('./views/error')),
  route('/:mailbox', require('./views/mailbox'), [
    route('/:message', require('./views/email'))
  ])
])
```
It would become:
```javascript
const app = choo()
app.router((route) => [
  route('/', require('./views/empty')),
  route('/404', require('./views/error')),
  route('/:mailbox', require('./views/mailbox'), [
    route('/:message', require('./views/email'))
  ])
], { default: '/404' }) // this last bit is optional
```
I personally found having `'/404'` as the first param in some of the examples confusing when I first started using choo. Didn't last long -- I figured it out, and the object syntax will make it more clear -- but that object feels more like an "options" object now, which I'd expect to be after the main routes array.

No big deal either way, just thought I'd throw it out there.

**Comment by yoshuawuyts** [comment]
Hah, yeah I see where you're coming from. Thanks for the feedback! I
slightly prefer the opts-first callback-last approach - imo the differences
are small enough it doesn't matter too much - hopefully having named
options will indeed help people out :D

**Comment by timwis** [comment]
Oh, interesting, I hadn't thought of the routes as callbacks. Seems more familiar if you think of them that way I suppose.
