### ISSUE TITLE
Replace const with var

### ISSUE THREAD

**Issue by aknuds1** [yoshuawuyts/sheet-router#78]
The [sheet-router npm package](https://www.npmjs.com/package/sheet-router) makes use of the `const` keyword. I guess it should be replaced with `var` before being packaged, no? I've had client errors cropping up on account of the `const` keyword, I suspect it's due to some browsers not treating it as lexically scoped.

**Comment by aknuds1** [comment]
How would you solve this? By using some babel transform to browserify, or perhaps just [varify](https://github.com/thlorenz/varify)?

**Comment by yoshuawuyts** [comment]
Recursive grep / ack and submitting a patch haha

**Comment by aknuds1** [comment]
OK, i guess I can do that. Is there a way to avoid this issue creeping back again though?
